# Pandas

- High-level data manipulation library
- Built upon Nump
- Two strucutres: **Series** and **DataFrames**

NumPy = foundation for numerical cimputing in Python
Pandas = uses NumPy under the hood. QUick calculations. NumPy arrays, pandas wraps around and adds metadata (index, columns, dtypes)

Use pandas to load data, inspect and clean, transform it, group and summarise and join and merge

**Pandas = NumPy Arrays + labels (index and columns) + alignment + missing values + convenience tools**

## Series

1-d NumPy-like arrays

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# Create a series from a list

my_list = [10,20,30,40]
x = pd.Series(my_list)
x

0    10
1    20
2    30
3    40
dtype: int64

- index: it's the label list
- values: the underlying NumPy array
- dtype - data type series

In [4]:
x.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
x.values

array([10, 20, 30, 40])

In [6]:
x.dtype

dtype('int64')

# Create a series with a customer index

In [11]:
data = [450,650,870] # my list
sales = Series(data, index=["PersonA", "PersonB", "PersonC"])
sales

PersonA    450
PersonB    650
PersonC    870
dtype: int64

In [9]:
sales.index

Index(['PersonA', 'PersonB', 'PersonC'], dtype='str')

In [12]:
type(sales)

pandas.Series

In [13]:
sales["PersonA"]

np.int64(450)

In [16]:
sales > 550

PersonA    False
PersonB     True
PersonC     True
dtype: bool

# Memebership Check

In [17]:
"PersonA" in sales

True

In [18]:
"Nish" in sales

False

In [19]:
450 in sales

False

# Work with dictionaries

In [20]:
sales_dict = sales.to_dict()
sales_dict

{'PersonA': 450, 'PersonB': 650, 'PersonC': 870}

In [21]:
sales_ser = Series(sales_dict)
sales_ser

PersonA    450
PersonB    650
PersonC    870
dtype: int64

In [22]:
new_sales = Series(sales, index=["PersonA","PersonB","Ramim","PersonC", "Hiyab"])
new_sales

PersonA    450.0
PersonB    650.0
Ramim        NaN
PersonC    870.0
Hiyab        NaN
dtype: float64

In [23]:
# Check for Nan

np.isnan(new_sales["Hiyab"])

np.True_

In [24]:
np.isnan(new_sales["PersonC"])

np.False_

In [27]:
# Naming component in series

sales.index.name = "Sales Person"
sales.name = "Total Laptop Sales"
sales

Sales Person
PersonA    450
PersonB    650
PersonC    870
Name: Total Laptop Sales, dtype: int64

# DataFrames

These are 2-d, size-mutable, mixed, tabular strucutres

Under the good:
- Each column is like series
- Columns can have different dtypes
- there ins shared row index

In [3]:
data = [["Atanaska", 20],["Abinash",12],["Erik",23]]
df = pd.DataFrame(data,columns=["Name","Height"])
df

       Name  Height
0  Atanaska      20
1   Abinash      12
2      Erik      23

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [34]:
# from a dictionart
new_dict = {
    "Name": ["Alpha", "Beta", "Gamma", "Delta"],
    "Sales":[250,300,350,400]
}
df_dict = pd.DataFrame(new_dict)
df_dict

    Name  Sales
0  Alpha    250
1   Beta    300
2  Gamma    350
3  Delta    400

## Add a custom index

The index is the ROW LABEL - this can be ranks, IDs dates, etc

In [36]:
df_dict_index = pd.DataFrame(new_dict, index=["rank1", "rank2","rank3","rank4"])
df_dict

    Name  Sales
0  Alpha    250
1   Beta    300
2  Gamma    350
3  Delta    400

## From list of dictionaries

In [38]:
dict_list = [
    {"Name": "Alpha", "Sales":250},
    {"Name": "Beta", "Sales":450},
    {"Name": "Gamma", "Sales":650},
    {"Name": "Delta", "Sales":850}
]

df_dict_list = pd.DataFrame(dict_list,index=["rank1", "rank2","rank3","rank4"])
df_dict_list

        Name  Sales
rank1  Alpha    250
rank2   Beta    450
rank3  Gamma    650
rank4  Delta    850

## DataFrame from a dictionary of series (alignment by index)

In [5]:
east = pd.Series([1000, 1200, 3400], index=["Q1", "Q2", "Q3"])
east

Q1    1000
Q2    1200
Q3    3400
dtype: int64

In [6]:
west = pd.Series([1100, 1300, 2400, 3500], index=["Q1", "Q2", "Q3", "Q4"])
west

Q1    1100
Q2    1300
Q3    2400
Q4    3500
dtype: int64

In [7]:
df_region = pd.DataFrame({"East": east, "West":west})
df_region

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

## Adding a column

In [8]:
df_region["North"] = [2000,3000,4000,5000]
df_region["South"] = [5435,543543,4760,7000]
df_region

      East  West  North   South
Q1  1000.0  1100   2000    5435
Q2  1200.0  1300   3000  543543
Q3  3400.0  2400   4000    4760
Q4     NaN  3500   5000    7000

## Shifting and changing the index

- Create a column
- set it as the index

In [9]:
years = ["2016","2017","2018","2019"]
df_region["years"] = years
df_region

      East  West  North   South years
Q1  1000.0  1100   2000    5435  2016
Q2  1200.0  1300   3000  543543  2017
Q3  3400.0  2400   4000    4760  2018
Q4     NaN  3500   5000    7000  2019

In [10]:
df_region = df_region.set_index("years")
df_region

         East  West  North   South
years
2016   1000.0  1100   2000    5435
2017   1200.0  1300   3000  543543
2018   3400.0  2400   4000    4760
2019      NaN  3500   5000    7000

1. Put this list of dictionaries into a dataframe
2. Print the shape of the dataframe
3. Create a new column called `average_mark` (we haven't covered this yet). and it should be the average of python, sql and nosql scores
4. Set `trainee` as the index and retrieve the row for Paula

In [12]:
data = [
    {"trainee": "Nish",  "cohort": "Tech-505", "python": 78, "sql": 66, "nosql": 72},
    {"trainee": "Cathy", "cohort": "Tech-505", "python": 91, "sql": 88, "nosql": 84},
    {"trainee": "David", "cohort": "Tech-505", "python": 55, "sql": 61, "nosql": 49},
    {"trainee": "Paula", "cohort": "Tech-506", "python": 69, "sql": 73, "nosql": 70},
    {"trainee": "Phil",  "cohort": "Tech-506", "python": 82, "sql": 79, "nosql": 75},
]

In [13]:

import pandas as pd

data = [
    {"trainee": "Nish",  "cohort": "Tech-505", "python": 78, "sql": 66, "nosql": 72},
    {"trainee": "Cathy", "cohort": "Tech-505", "python": 91, "sql": 88, "nosql": 84},
    {"trainee": "David", "cohort": "Tech-505", "python": 55, "sql": 61, "nosql": 49},
    {"trainee": "Paula", "cohort": "Tech-506", "python": 69, "sql": 73, "nosql": 70},
    {"trainee": "Phil",  "cohort": "Tech-506", "python": 82, "sql": 79, "nosql": 75},
]

# 1. Create DataFrame
df = pd.DataFrame(data)
print(df)
# 2. Shape
print(df.shape)

# 3. Average mark
df["average_mark"] = df[["python", "sql", "nosql"]].mean(axis=1)
print(df)

# 4. Indexing
df_indexed = df.set_index("trainee")
df_indexed.loc["Paula"]

  trainee    cohort  python  sql  nosql
0    Nish  Tech-505      78   66     72
1   Cathy  Tech-505      91   88     84
2   David  Tech-505      55   61     49
3   Paula  Tech-506      69   73     70
4    Phil  Tech-506      82   79     75
(5, 5)
  trainee    cohort  python  sql  nosql  average_mark
0    Nish  Tech-505      78   66     72     72.000000
1   Cathy  Tech-505      91   88     84     87.666667
2   David  Tech-505      55   61     49     55.000000
3   Paula  Tech-506      69   73     70     70.666667
4    Phil  Tech-506      82   79     75     78.666667

cohort           Tech-506
python                 69
sql                    73
nosql                  70
average_mark    70.666667
Name: Paula, dtype: object

## Reindexing

`reindex` that changes the index to a new set of labels:

- Take the new index you ask for
- Aligns existing data by label
- Add rows for missing labels
- Inserts NaN where data does not exist
- Drops and old labels not in de the index

In [14]:
df_region

         East  West  North   South
years
2016   1000.0  1100   2000    5435
2017   1200.0  1300   3000  543543
2018   3400.0  2400   4000    4760
2019      NaN  3500   5000    7000

In [17]:
new_df = df_region.reindex(["2017","2018","2019","2020","2021"])
new_df

         East    West   North     South
years
2017   1200.0  1300.0  3000.0  543543.0
2018   3400.0  2400.0  4000.0    4760.0
2019      NaN  3500.0  5000.0    7000.0
2020      NaN     NaN     NaN       NaN
2021      NaN     NaN     NaN       NaN

### Reindex columns


- reorder existing
- add new columns (filled by Nan)

In [20]:
re_indexed = new_df.reindex(columns=["North", "East", "South", "New"])
re_indexed

        North    East     South  New
years
2017   3000.0  1200.0  543543.0  NaN
2018   4000.0  3400.0    4760.0  NaN
2019   5000.0     NaN    7000.0  NaN
2020      NaN     NaN       NaN  NaN
2021      NaN     NaN       NaN  NaN

## Missing Data

In [28]:
re_indexed = re_indexed.fillna(0)
re_indexed

        North    East     South  New
years
2017   3000.0  1200.0  543543.0  0.0
2018   4000.0  3400.0    4760.0  0.0
2019   5000.0     0.0    7000.0  0.0
2020      0.0     0.0       0.0  0.0
2021      0.0     0.0       0.0  0.0

In [29]:
re_indexed = re_indexed.interpolate()
re_indexed

        North    East     South  New
years
2017   3000.0  1200.0  543543.0  0.0
2018   4000.0  3400.0    4760.0  0.0
2019   5000.0     0.0    7000.0  0.0
2020      0.0     0.0       0.0  0.0
2021      0.0     0.0       0.0  0.0

In [31]:
# Drop missing data

re_indexed = re_indexed.dropna(axis=1, how='all')
re_indexed

        North    East     South  New
years
2017   3000.0  1200.0  543543.0  0.0
2018   4000.0  3400.0    4760.0  0.0
2019   5000.0     0.0    7000.0  0.0
2020      0.0     0.0       0.0  0.0
2021      0.0     0.0       0.0  0.0

# Duplicates

- `duplicated()` - returns a bool
- `drop_duplicates()` removes duplicates rows

In [38]:
df_dup = DataFrame([["A", 1], ["B", 2], ["A", 1]], columns=["Letter", "Number"])
df_dup

  Letter  Number
0      A       1
1      B       2
2      A       1

In [39]:
df_dup.duplicated()

0    False
1    False
2     True
dtype: bool

In [40]:
df_dup2 = df_dup.drop_duplicates()
df_dup2

  Letter  Number
0      A       1
1      B       2

## Selected entries

- `df["col"]` select columns
- `iloc` selects by position
- `loc` selects by label

In [41]:
new_df

         East    West   North     South
years
2017   1200.0  1300.0  3000.0  543543.0
2018   3400.0  2400.0  4000.0    4760.0
2019      NaN  3500.0  5000.0    7000.0
2020      NaN     NaN     NaN       NaN
2021      NaN     NaN     NaN       NaN

In [42]:
new_df["North"]

years
2017    3000.0
2018    4000.0
2019    5000.0
2020       NaN
2021       NaN
Name: North, dtype: float64

In [45]:
new_df.iloc[0,1]

np.float64(1300.0)

In [46]:
new_df.iloc[1:3]

         East    West   North   South
years
2018   3400.0  2400.0  4000.0  4760.0
2019      NaN  3500.0  5000.0  7000.0

In [48]:
new_df.loc[["2019","2018"]]

         East    West   North   South
years
2019      NaN  3500.0  5000.0  7000.0
2018   3400.0  2400.0  4000.0  4760.0

## Data Aligment

When we do arithmetic pandas aligns by index label

In [51]:
new_df["East"]

years
2017    1200.0
2018    3400.0
2019       NaN
2020       NaN
2021       NaN
Name: East, dtype: float64

In [52]:
new_df["North"]

years
2017    3000.0
2018    4000.0
2019    5000.0
2020       NaN
2021       NaN
Name: North, dtype: float64

In [54]:
new_df["East"].add(new_df["North"]).fillna(0)

years
2017    4200.0
2018    7400.0
2019       0.0
2020       0.0
2021       0.0
dtype: float64

## summary stats

In [55]:
new_df.describe()

              East    West   North          South
count     2.000000     3.0     3.0       3.000000
mean   2300.000000  2400.0  4000.0  185101.000000
std    1555.634919  1100.0  1000.0  310421.898266
min    1200.000000  1300.0  3000.0    4760.000000
25%    1750.000000  1850.0  3500.0    5880.000000
50%    2300.000000  2400.0  4000.0    7000.000000
75%    2850.000000  2950.0  4500.0  275271.500000
max    3400.000000  3500.0  5000.0  543543.000000

In [56]:
new_df.sum()

East       4600.0
West       7200.0
North     12000.0
South    555303.0
dtype: float64

In [57]:
new_df.sum(numeric_only=True)

East       4600.0
West       7200.0
North     12000.0
South    555303.0
dtype: float64

In [58]:
new_df.count()

East     2
West     3
North    3
South    3
dtype: int64

In [61]:
new_df.max(numeric_only=True)

East       3400.0
West       3500.0
North      5000.0
South    543543.0
dtype: float64

## Exercise

```python
data_sales_2026 = [
    {"month": "Jan", "revenue": 1800},
    {"month": "Feb", "revenue": 2200},
    {"month": "Mar", "revenue": None},
    {"month": "Apr", "revenue": 2600},
    {"month": "Feb", "revenue": 2200},
    {"month": "Jun", "revenue": 3100},
]
```

1. Create a dataframe called `df_data` and set month as the index
2. Remove duplicate months (keep the first occurence)
3. Reindex the DataFrame so it contains all months from Jan to Jun
4. Replace 0 values with interpolation (you will need to changes values to numeric)
5. Selected months where revenue > 2000
6. Use `'iloc` to seect rows as positions `1:4`
7. Create a new data frame showing total revenue for 2026
8. Sory the DataFrame by revenue in descending order