# Pandas

- High-level data manipulation library
- Built upon Nump
- Two strucutres: **Series** and **DataFrames**

NumPy = foundation for numerical cimputing in Python
Pandas = uses NumPy under the hood. QUick calculations. NumPy arrays, pandas wraps around and adds metadata (index, columns, dtypes)

Use pandas to load data, inspect and clean, transform it, group and summarise and join and merge

**Pandas = NumPy Arrays + labels (index and columns) + alignment + missing values + convenience tools**

## Series

1-d NumPy-like arrays

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# Create a series from a list

my_list = [10,20,30,40]
x = pd.Series(my_list)
x

0    10
1    20
2    30
3    40
dtype: int64

- index: it's the label list
- values: the underlying NumPy array
- dtype - data type series

In [4]:
x.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
x.values

array([10, 20, 30, 40])

In [6]:
x.dtype

dtype('int64')

# Create a series with a customer index

In [11]:
data = [450,650,870] # my list
sales = Series(data, index=["PersonA", "PersonB", "PersonC"])
sales

PersonA    450
PersonB    650
PersonC    870
dtype: int64

In [9]:
sales.index

Index(['PersonA', 'PersonB', 'PersonC'], dtype='str')

In [12]:
type(sales)

pandas.Series

In [13]:
sales["PersonA"]

np.int64(450)

In [16]:
sales > 550

PersonA    False
PersonB     True
PersonC     True
dtype: bool

# Memebership Check

In [17]:
"PersonA" in sales

True

In [18]:
"Nish" in sales

False

In [19]:
450 in sales

False

# Work with dictionaries

In [20]:
sales_dict = sales.to_dict()
sales_dict

{'PersonA': 450, 'PersonB': 650, 'PersonC': 870}

In [21]:
sales_ser = Series(sales_dict)
sales_ser

PersonA    450
PersonB    650
PersonC    870
dtype: int64

In [22]:
new_sales = Series(sales, index=["PersonA","PersonB","Ramim","PersonC", "Hiyab"])
new_sales

PersonA    450.0
PersonB    650.0
Ramim        NaN
PersonC    870.0
Hiyab        NaN
dtype: float64

In [23]:
# Check for Nan

np.isnan(new_sales["Hiyab"])

np.True_

In [24]:
np.isnan(new_sales["PersonC"])

np.False_

In [27]:
# Naming component in series

sales.index.name = "Sales Person"
sales.name = "Total Laptop Sales"
sales

Sales Person
PersonA    450
PersonB    650
PersonC    870
Name: Total Laptop Sales, dtype: int64

# DataFrames

These are 2-d, size-mutable, mixed, tabular strucutres

Under the good:
- Each column is like series
- Columns can have different dtypes
- there ins shared row index

In [28]:
data = [["Atanaska", 20],["Abinash",12],["Erik",23]]
df = pd.DataFrame(data,columns=["Name","Height"])
df

       Name  Height
0  Atanaska      20
1   Abinash      12
2      Erik      23

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [34]:
# from a dictionart
new_dict = {
    "Name": ["Alpha", "Beta", "Gamma", "Delta"],
    "Sales":[250,300,350,400]
}
df_dict = pd.DataFrame(new_dict)
df_dict

    Name  Sales
0  Alpha    250
1   Beta    300
2  Gamma    350
3  Delta    400

## Add a custom index

The index is the ROW LABEL - this can be ranks, IDs dates, etc

In [36]:
df_dict_index = pd.DataFrame(new_dict, index=["rank1", "rank2","rank3","rank4"])
df_dict

    Name  Sales
0  Alpha    250
1   Beta    300
2  Gamma    350
3  Delta    400

## From list of dictionaries

In [38]:
dict_list = [
    {"Name": "Alpha", "Sales":250},
    {"Name": "Beta", "Sales":450},
    {"Name": "Gamma", "Sales":650},
    {"Name": "Delta", "Sales":850}
]

df_dict_list = pd.DataFrame(dict_list,index=["rank1", "rank2","rank3","rank4"])
df_dict_list

        Name  Sales
rank1  Alpha    250
rank2   Beta    450
rank3  Gamma    650
rank4  Delta    850

## DataFrame from a dictionary of series (alignment by index)

In [42]:
east = pd.Series([1000, 1200, 3400], index=["Q1", "Q2", "Q3"])
east

Q1    1000
Q2    1200
Q3    3400
dtype: int64

In [43]:
west = pd.Series([1100, 1300, 2400, 3500], index=["Q1", "Q2", "Q3", "Q4"])
west

Q1    1100
Q2    1300
Q3    2400
Q4    3500
dtype: int64

In [46]:
df_region = pd.DataFrame({"East": east, "West":west})
df_region

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

## Adding a column

In [47]:
df_region["North"] = [2000,3000,4000,5000]
df_region["South"] = [5435,543543,4760,7000]
df_region

      East  West  North   South
Q1  1000.0  1100   2000    5435
Q2  1200.0  1300   3000  543543
Q3  3400.0  2400   4000    4760
Q4     NaN  3500   5000    7000

## Shifting and changing the index

- Create a column
- set it as the index

In [49]:
years = ["2016","2017","2018","2019"]
df_region["years"] = years
df_region

      East  West  North   South years
Q1  1000.0  1100   2000    5435  2016
Q2  1200.0  1300   3000  543543  2017
Q3  3400.0  2400   4000    4760  2018
Q4     NaN  3500   5000    7000  2019

In [50]:
df_region = df_region.set_index("years")
df_region

         East  West  North   South
years
2016   1000.0  1100   2000    5435
2017   1200.0  1300   3000  543543
2018   3400.0  2400   4000    4760
2019      NaN  3500   5000    7000

1. Put this list of dictionaries into a dataframe
2. Print the shape of the dataframe
3. Create a new column called `average_mark` (we haven't covered this yet). and it should be the average of python, sql and nosql scores
4. Set `trainee` as the index and retrieve the row for Paula

In [ ]:
data = [
    {"trainee": "Nish",  "cohort": "Tech-505", "python": 78, "sql": 66, "nosql": 72},
    {"trainee": "Cathy", "cohort": "Tech-505", "python": 91, "sql": 88, "nosql": 84},
    {"trainee": "David", "cohort": "Tech-505", "python": 55, "sql": 61, "nosql": 49},
    {"trainee": "Paula", "cohort": "Tech-506", "python": 69, "sql": 73, "nosql": 70},
    {"trainee": "Phil",  "cohort": "Tech-506", "python": 82, "sql": 79, "nosql": 75},
]