# Working with data


- Read CSV files
- Inspecting data (head tails)
- `groupby` basics
- JSON loading
- Merging
- Concatenation
- Filling missing values by combining
- Reshaping `pivot`, `stack` and `unstack`
- Crosstabulation...?

In [29]:
import numpy as mp
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# optional - just a nicer display for our tables
pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 120)

## CSV files

`pd.read_csv()` - loads csv into a `DataFrame`

- `sep` (delimeter)
- `header` (which row contains column names (defualt is inferred based on first row)
- `na_values` (treat certais string as missing values

In [4]:
iris = pd.read_csv("iris.csv")
iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [5]:
iris = pd.read_csv("iris.csv", sep=",", header="infer")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
# Inspect data further
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [7]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Writing to CSV

- `to_csv` to write a dataframe to a file. Parameters:
    - `index` (include index columns or not)
    - `sep` (delimter)

In [10]:
iris.to_csv("new_iris.csv", index=False)
# import os
# os.getcwd()

'C:\\GitHub\\Data601\\PythonFundamentals\\main\\python-with-data'

In [11]:
# preview csv on screen

import sys

iris.to_csv(sys.stdout, sep="_", index=False)

"sepal_length"_"sepal_width"_"petal_length"_"petal_width"_species
5.1_3.5_1.4_0.2_setosa
4.9_3.0_1.4_0.2_setosa
4.7_3.2_1.3_0.2_setosa
4.6_3.1_1.5_0.2_setosa
5.0_3.6_1.4_0.2_setosa
5.4_3.9_1.7_0.4_setosa
4.6_3.4_1.4_0.3_setosa
5.0_3.4_1.5_0.2_setosa
4.4_2.9_1.4_0.2_setosa
4.9_3.1_1.5_0.1_setosa
5.4_3.7_1.5_0.2_setosa
4.8_3.4_1.6_0.2_setosa
4.8_3.0_1.4_0.1_setosa
4.3_3.0_1.1_0.1_setosa
5.8_4.0_1.2_0.2_setosa
5.7_4.4_1.5_0.4_setosa
5.4_3.9_1.3_0.4_setosa
5.1_3.5_1.4_0.3_setosa
5.7_3.8_1.7_0.3_setosa
5.1_3.8_1.5_0.3_setosa
5.4_3.4_1.7_0.2_setosa
5.1_3.7_1.5_0.4_setosa
4.6_3.6_1.0_0.2_setosa
5.1_3.3_1.7_0.5_setosa
4.8_3.4_1.9_0.2_setosa
5.0_3.0_1.6_0.2_setosa
5.0_3.4_1.6_0.4_setosa
5.2_3.5_1.5_0.2_setosa
5.2_3.4_1.4_0.2_setosa
4.7_3.2_1.6_0.2_setosa
4.8_3.1_1.6_0.2_setosa
5.4_3.4_1.5_0.4_setosa
5.2_4.1_1.5_0.1_setosa
5.5_4.2_1.4_0.2_setosa
4.9_3.1_1.5_0.1_setosa
5.0_3.2_1.2_0.2_setosa
5.5_3.5_1.3_0.2_setosa
4.9_3.1_1.5_0.1_setosa
4.4_3.0_1.3_0.2_setosa
5.1_3.4_1.5_0.2_setosa
5.0_3.5_1.3_0.3_setosa
4.5_2.3_1.3_0.3_setosa
4.4_3.2_1.3_0.2_setosa
5.0_3.5_1.6_0.6_setosa
5.1_3.8_1.9_0.4_setosa
4.8_3.0_1.4_0.3_setosa
5.1_3.8_1.6_0.2_setosa
4.6_3.2_1.4_0.2_setosa
5.3_3.7_1.5_0.2_setosa
5.0_3.3_1.4_0.2_setosa
7.0_3.2_4.7_1.4_versicolor
6.4_3.2_4.5_1.5_versicolor
6.9_3.1_4.9_1.5_versicolor
5.5_2.3_4.0_1.3_versicolor
6.5_2.8_4.6_1.5_versicolor
5.7_2.8_4.5_1.3_versicolor
6.3_3.3_4.7_1.6_versicolor
4.9_2.4_3.3_1.0_versicolor
6.6_2.9_4.6_1.3_versicolor
5.2_2.7_3.9_1.4_versicolor
5.0_2.0_3.5_1.0_versicolor
5.9_3.0_4.2_1.5_versicolor
6.0_2.2_4.0_1.0_versicolor
6.1_2.9_4.7_1.4_versicolor
5.6_2.9_3.6_1.3_versicolor
6.7_3.1_4.4_1.4_versicolor
5.6_3.0_4.5_1.5_versicolor
5.8_2.7_4.1_1.0_versicolor
6.2_2.2_4.5_1.5_versicolor
5.6_2.5_3.9_1.1_versicolor
5.9_3.2_4.8_1.8_versicolor
6.1_2.8_4.0_1.3_versicolor
6.3_2.5_4.9_1.5_versicolor
6.1_2.8_4.7_1.2_versicolor
6.4_2.9_4.3_1.3_versicolor
6.6_3.0_4.4_1.4_versicolor
6.8_2.8_4.8_1.4_versicolor
6.7_3.0_5.0_1.7_versicolor
6.0_2.9_4.5_1.5_versicolor
5.7_2.6_3.5_1.0_versicolor
5.5_2.4_3.8_1.1_versicolor
5.5_2.4_3.7_1.0_versicolor
5.8_2.7_3.9_1.2_versicolor
6.0_2.7_5.1_1.6_versicolor
5.4_3.0_4.5_1.5_versicolor
6.0_3.4_4.5_1.6_versicolor
6.7_3.1_4.7_1.5_versicolor
6.3_2.3_4.4_1.3_versicolor
5.6_3.0_4.1_1.3_versicolor
5.5_2.5_4.0_1.3_versicolor
5.5_2.6_4.4_1.2_versicolor
6.1_3.0_4.6_1.4_versicolor
5.8_2.6_4.0_1.2_versicolor
5.0_2.3_3.3_1.0_versicolor
5.6_2.7_4.2_1.3_versicolor
5.7_3.0_4.2_1.2_versicolor
5.7_2.9_4.2_1.3_versicolor
6.2_2.9_4.3_1.3_versicolor
5.1_2.5_3.0_1.1_versicolor
5.7_2.8_4.1_1.3_versicolor
6.3_3.3_6.0_2.5_virginica
5.8_2.7_5.1_1.9_virginica
7.1_3.0_5.9_2.1_virginica
6.3_2.9_5.6_1.8_virginica
6.5_3.0_5.8_2.2_virginica
7.6_3.0_6.6_2.1_virginica
4.9_2.5_4.5_1.7_virginica
7.3_2.9_6.3_1.8_virginica
6.7_2.5_5.8_1.8_virginica
7.2_3.6_6.1_2.5_virginica
6.5_3.2_5.1_2.0_virginica
6.4_2.7_5.3_1.9_virginica
6.8_3.0_5.5_2.1_virginica
5.7_2.5_5.0_2.0_virginica
5.8_2.8_5.1_2.4_virginica
6.4_3.2_5.3_2.3_virginica
6.5_3.0_5.5_1.8_virginica
7.7_3.8_6.7_2.2_virginica
7.7_2.6_6.9_2.3_virginica
6.0_2.2_5.0_1.5_virginica
6.9_3.2_5.7_2.3_virginica
5.6_2.8_4.9_2.0_virginica
7.7_2.8_6.7_2.0_virginica
6.3_2.7_4.9_1.8_virginica
6.7_3.3_5.7_2.1_virginica
7.2_3.2_6.0_1.8_virginica
6.2_2.8_4.8_1.8_virginica
6.1_3.0_4.9_1.8_virginica
6.4_2.8_5.6_2.1_virginica
7.2_3.0_5.8_1.6_virginica
7.4_2.8_6.1_1.9_virginica
7.9_3.8_6.4_2.0_virginica
6.4_2.8_5.6_2.2_virginica
6.3_2.8_5.1_1.5_virginica
6.1_2.6_5.6_1.4_virginica
7.7_3.0_6.1_2.3_virginica
6.3_3.4_5.6_2.4_virginica
6.4_3.1_5.5_1.8_virginica
6.0_3.0_4.8_1.8_virginica
6.9_3.1_5.4_2.1_virginica
6.7_3.1_5.6_2.4_virginica
6.9_3.1_5.1_2.3_virginica
5.8_2.7_5.1_1.9_virginica
6.8_3.2_5.9_2.3_virginica
6.7_3.3_5.7_2.5_virginica
6.7_3.0_5.2_2.3_virginica
6.3_2.5_5.0_1.9_virginica
6.5_3.0_5.2_2.0_virginica
6.2_3.4_5.4_2.3_virginica
5.9_3.0_5.1_1.8_virginica

## `groupby`

- Split our dataframe into groups based on a key columns. In our case it will be **species**
- Remember `groupby` does NOT immediately compute something. We need to apply an aggregatation function (`sum` etc)

In [12]:
spec = iris.groupby("species")
spec

In [13]:
spec.head(10)

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
6             4.6          3.4           1.4          0.3      setosa
7             5.0          3.4           1.5          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
55            5.7          2.8           4.5          1.3  versicolor
56            6.3          3.3           4.7          1.6  versicolor
57            4.9          2.4           3.3          1.0  versicolor
58            6.6          2.9           4.6          1.3  versicolor
59            5.2          2.7           3.9          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
106           4.9          2.5           4.5          1.7   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica

In [15]:
spec.mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

## Exercise

 Use the Iris data set to do the following:

1. Add a `rank` column raanking `petal_length` in ascending order
2. Find the mean for each numeric olumn for each species
3. Create a new DataFrame per species (3 total)
4. Create 2 DataFrames:
    - one for **Sepal** info (length + width + species)
    - one for **Petal** info (length + width + species)

In [16]:
# 1
iris["petal_length_rank"] = iris["petal_length"].rank(method="first", ascending=True)

iris[["petal_length", "petal_length_rank", "species"]].head(10)
iris

     sepal_length  sepal_width  petal_length  petal_width    species  petal_length_rank
0             5.1          3.5           1.4          0.2     setosa               12.0
1             4.9          3.0           1.4          0.2     setosa               13.0
2             4.7          3.2           1.3          0.2     setosa                5.0
3             4.6          3.1           1.5          0.2     setosa               24.0
4             5.0          3.6           1.4          0.2     setosa               14.0
..            ...          ...           ...          ...        ...                ...
145           6.7          3.0           5.2          2.3  virginica              117.0
146           6.3          2.5           5.0          1.9  virginica              108.0
147           6.5          3.0           5.2          2.0  virginica              118.0
148           6.2          3.4           5.4          2.3  virginica              122.0
149           5.9          3.0           5.1          1.8  virginica              116.0

[150 rows x 6 columns]

In [17]:
# 2
means_by_species = iris.groupby("species").mean()
means_by_species

            sepal_length  sepal_width  petal_length  petal_width  petal_length_rank
species
setosa             5.006        3.418         1.464        0.244              25.50
versicolor         5.936        2.770         4.260        1.326              76.12
virginica          6.588        2.974         5.552        2.026             124.88

In [21]:
# 3
vers = iris[iris["species"] == "versicolor"]
setosa = iris[iris["species"] == "setosa"]
virg = iris[iris["species"] == "virginica"]

vers.head(),
setosa.head(),
virg.head()

     sepal_length  sepal_width  petal_length  petal_width    species  petal_length_rank
100           6.3          3.3           6.0          2.5  virginica              140.0
101           5.8          2.7           5.1          1.9  virginica              110.0
102           7.1          3.0           5.9          2.1  virginica              138.0
103           6.3          2.9           5.6          1.8  virginica              126.0
104           6.5          3.0           5.8          2.2  virginica              135.0

In [19]:
sepal_info = iris[["sepal_length", "sepal_width", "species"]].copy()
petal_info = iris[["petal_length", "petal_width", "species"]].copy()

sepal_info.head(), petal_info.head()

(   sepal_length  sepal_width species
 0           5.1          3.5  setosa
 1           4.9          3.0  setosa
 2           4.7          3.2  setosa
 3           4.6          3.1  setosa
 4           5.0          3.6  setosa,
    petal_length  petal_width species
 0           1.4          0.2  setosa
 1           1.4          0.2  setosa
 2           1.3          0.2  setosa
 3           1.5          0.2  setosa
 4           1.4          0.2  setosa)

## JSON file sin Pandas

In [22]:
iris_json = pd.read_json("iris.json")
iris_json.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

## Merging DataFrames

You can merge when you have *related* data split across multiple DataFrames. Two common scenarios:

1. Merge on Index - noth DFs line up by their index
2. Merge on key columns -  joins like SQL using IDs

In [26]:
sepal_info = iris[["sepal_length", "sepal_width", "species"]].copy()
petal_info = iris[["petal_length", "petal_width", "species"]].copy()

# Merging on their row index NOT a column
# inner keeps only row where the index exists in both data frames
# left_index - and right_index = true. Tells pandas to join on the index (i.e.g use sepal_info index as the join key, and petal_info index as the join

merge_on_index = pd.merge(sepal_info,petal_info,how="inner", left_index=True, right_index=True)
merge_on_index

     sepal_length  sepal_width  species_x  petal_length  petal_width  species_y
0             5.1          3.5     setosa           1.4          0.2     setosa
1             4.9          3.0     setosa           1.4          0.2     setosa
2             4.7          3.2     setosa           1.3          0.2     setosa
3             4.6          3.1     setosa           1.5          0.2     setosa
4             5.0          3.6     setosa           1.4          0.2     setosa
..            ...          ...        ...           ...          ...        ...
145           6.7          3.0  virginica           5.2          2.3  virginica
146           6.3          2.5  virginica           5.0          1.9  virginica
147           6.5          3.0  virginica           5.2          2.0  virginica
148           6.2          3.4  virginica           5.4          2.3  virginica
149           5.9          3.0  virginica           5.1          1.8  virginica

[150 rows x 6 columns]

### Merge on key columns

In [31]:
sepal_info_with_id = sepal_info.copy()
petal_info_with_id = petal_info.copy()

# add a column called sepal_id
sepal_info_with_id["sepal_id"] = np.arange(len(sepal_info_with_id)) # generate values from 0 to number of rows in the df -1
petal_info_with_id["petal_id"] = np.arange(len(petal_info_with_id)) # generate values from 0 to number of rows in the df -1
petal_info_with_id

     petal_length  petal_width    species  petal_id
0             1.4          0.2     setosa         0
1             1.4          0.2     setosa         1
2             1.3          0.2     setosa         2
3             1.5          0.2     setosa         3
4             1.4          0.2     setosa         4
..            ...          ...        ...       ...
145           5.2          2.3  virginica       145
146           5.0          1.9  virginica       146
147           5.2          2.0  virginica       147
148           5.4          2.3  virginica       148
149           5.1          1.8  virginica       149

[150 rows x 4 columns]

In [32]:
# merge the two data frames

merged_on_ids = pd.merge(sepal_info_with_id,petal_info_with_id,left_on="sepal_id",right_on="petal_id",how="inner")
merged_on_ids

     sepal_length  sepal_width  species_x  sepal_id  petal_length  petal_width  species_y  petal_id
0             5.1          3.5     setosa         0           1.4          0.2     setosa         0
1             4.9          3.0     setosa         1           1.4          0.2     setosa         1
2             4.7          3.2     setosa         2           1.3          0.2     setosa         2
3             4.6          3.1     setosa         3           1.5          0.2     setosa         3
4             5.0          3.6     setosa         4           1.4          0.2     setosa         4
..            ...          ...        ...       ...           ...          ...        ...       ...
145           6.7          3.0  virginica       145           5.2          2.3  virginica       145
146           6.3          2.5  virginica       146           5.0          1.9  virginica       146
147           6.5          3.0  virginica       147           5.2          2.0  virginica       147
148           6.2          3.4  virginica       148           5.4          2.3  virginica       148
149           5.9          3.0  virginica       149           5.1          1.8  virginica       149

[150 rows x 8 columns]

## Concatentation

`pd.concat` used to stack DataFrames vertically (i.e. add more rows) annd it can take an argument `axis=1` to combine side-by-side (add more columns), assuming the index is aligned

In [37]:
stacked = pd.concat([vers,setosa], axis=0, ignore_index=True)
stacked

    sepal_length  sepal_width  petal_length  petal_width     species  petal_length_rank
50           7.0          3.2           4.7          1.4  versicolor               91.0
51           6.4          3.2           4.5          1.5  versicolor               80.0
52           6.9          3.1           4.9          1.5  versicolor              100.0
53           5.5          2.3           4.0          1.3  versicolor               62.0
54           6.5          2.8           4.6          1.5  versicolor               88.0
..           ...          ...           ...          ...         ...                ...
45           4.8          3.0           1.4          0.3      setosa               21.0
46           5.1          3.8           1.6          0.2      setosa               44.0
47           4.6          3.2           1.4          0.2      setosa               22.0
48           5.3          3.7           1.5          0.2      setosa               37.0
49           5.0          3.3           1.4          0.2      setosa               23.0

[100 rows x 6 columns]

## Combining Data Frames

`combine_first` - fill in missing values in one DataFrame with values from another position

In [39]:
sales1 = pd.DataFrame({
    "East":  [1500, np.nan, 3500, np.nan],
    "West":  [np.nan, 4500, np.nan, 5500],
    "South": [6500, np.nan, 7500, np.nan]
})


sales1

     East    West   South
0  1500.0     NaN  6500.0
1     NaN  4500.0     NaN
2  3500.0     NaN  7500.0
3     NaN  5500.0     NaN

In [41]:
sales2 = pd.DataFrame({
    "East": [1200, 1300, np.nan, 1600, 1800],
    "West": [np.nan, 5000, 6000, 7000, 8000]
})
sales2

     East    West
0  1200.0     NaN
1  1300.0  5000.0
2     NaN  6000.0
3  1600.0  7000.0
4  1800.0  8000.0

In [43]:
combined_sales = sales1.combine_first(sales2)
combined_sales

     East    West   South
0  1500.0     NaN  6500.0
1  1300.0  4500.0     NaN
2  3500.0  6000.0  7500.0
3  1600.0  5500.0     NaN
4  1800.0  8000.0     NaN

3 different combinations methods: `merge`,`concat` and `combine_first`

## Reshaping with pivot, stack and unstack

- `Long format` - one measurement per row (e.g. year, month, passenger)
- `Wide format` - the values are spread across columns (e.g. months as columns)

We will be using `seaborn` which is used for data viz

It also comes along with a few sample datasets

In [44]:
import seaborn as sns
print(sns.get_data_home()) #where this data lies

C:\Users\Nishant Mandal\AppData\Local\seaborn\seaborn\Cache

In [45]:
flights = sns.load_dataset("flights")
flights.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [46]:
## PivoT - long to wide
# index=year -> row becomes year
# columns="month" -> each month becomes a column
# values="passengers" -> the cell values are passenger count

flights_piv = flights.pivot(
    index="year",
    columns="month",
    values="passengers"
)

flights_piv

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201
1954   204  188  235  227  234  264  302  293  259  229  203  229
1955   242  233  267  269  270  315  364  347  312  274  237  278
1956   284  277  317  313  318  374  413  405  355  306  271  306
1957   315  301  356  348  355  422  465  467  404  347  305  336
1958   340  318  362  348  363  435  491  505  404  359  310  337
1959   360  342  406  396  420  472  548  559  463  407  362  405
1960   417  391  419  461  472  535  622  606  508  461  390  432

In [48]:
# Stack: wide -> long

# stack() moves the columns labels (months) down into the index
# This create a multiindex (year, month)
# the result is a series NOT a dataframe

flight_stack = flights_piv.stack()
flight_stack.head(10)

year  month
1949  Jan      112
      Feb      118
      Mar      132
      Apr      129
      May      121
      Jun      135
      Jul      148
      Aug      148
      Sep      136
      Oct      119
dtype: int64

In [50]:
flights_piv.index

Index([1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960], dtype='int64', name='year')

In [49]:
flight_stack.index

MultiIndex([(1949, 'Jan'),
            (1949, 'Feb'),
            (1949, 'Mar'),
            (1949, 'Apr'),
            (1949, 'May'),
            (1949, 'Jun'),
            (1949, 'Jul'),
            (1949, 'Aug'),
            (1949, 'Sep'),
            (1949, 'Oct'),
            ...
            (1960, 'Mar'),
            (1960, 'Apr'),
            (1960, 'May'),
            (1960, 'Jun'),
            (1960, 'Jul'),
            (1960, 'Aug'),
            (1960, 'Sep'),
            (1960, 'Oct'),
            (1960, 'Nov'),
            (1960, 'Dec')],
           names=['year', 'month'], length=144)

In [51]:
# name the unnamed columns
flight_stack = flight_stack.rename("passengers")
flight_stack

year  month
1949  Jan      112
      Feb      118
      Mar      132
      Apr      129
      May      121
              ...
1960  Aug      606
      Sep      508
      Oct      461
      Nov      390
      Dec      432
Name: passengers, Length: 144, dtype: int64

In [52]:
## Unpivot long->wide

flights_unstack = flight_stack.unstack()

flights_unstack.head()

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201

## Crosstabulation

Creates a frequency table e.g. how many rows per species have each petal_width value

In [53]:
pd.crosstab(iris["species"], iris["petal_width"])

petal_width,0.1,0.2,0.3,0.4,0.5,0.6,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.1,2.2,2.3,2.4,2.5
species,,,,,,,,,,,,,,,,,,,,,,
setosa,6,28,7,7,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
versicolor,0,0,0,0,0,0,7,3,5,13,7,10,3,1,1,0,0,0,0,0,0,0
virginica,0,0,0,0,0,0,0,0,0,0,1,2,1,1,11,5,6,6,3,8,3,3

## Exercise

1. Clean the Titanic dataset
    - Identifying missing values
    - Decide what to fill vs what to drop
    - Check duplicates
2. Find the average fare and age for each class
3. Add a new column showing fates as % of the total ffare
4. How many survivors were femal comapred to male
5. Insights?

In [54]:
import pandas as pd
import numpy
from pandas import DataFrame
import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True