# Working with data


- Read CSV files
- Inspecting data (head tails)
- `groupby` basics
- JSON loading
- Merging
- Concatenation
- Filling missing values by combining
- Reshaping `pivot`, `stack` and `unstack`
- Crosstabulation...?

In [2]:
import numpy as mp
import pandas as pd
from pandas import Series, DataFrame

# optional - just a nicer display for our tables
pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 120)

## CSV files

`pd.read_csv()` - loads csv into a `DataFrame`

- `sep` (delimeter)
- `header` (which row contains column names (defualt is inferred based on first row)
- `na_values` (treat certais string as missing values

In [4]:
iris = pd.read_csv("iris.csv")
iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [5]:
iris = pd.read_csv("iris.csv", sep=",", header="infer")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
# Inspect data further
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [7]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Writing to CSV

- `to_csv` to write a dataframe to a file. Parameters:
    - `index` (include index columns or not)
    - `sep` (delimter)

In [10]:
iris.to_csv("new_iris.csv", index=False)
# import os
# os.getcwd()

'C:\\GitHub\\Data601\\PythonFundamentals\\main\\python-with-data'

In [11]:
# preview csv on screen

import sys

iris.to_csv(sys.stdout, sep="_", index=False)

"sepal_length"_"sepal_width"_"petal_length"_"petal_width"_species
5.1_3.5_1.4_0.2_setosa
4.9_3.0_1.4_0.2_setosa
4.7_3.2_1.3_0.2_setosa
4.6_3.1_1.5_0.2_setosa
5.0_3.6_1.4_0.2_setosa
5.4_3.9_1.7_0.4_setosa
4.6_3.4_1.4_0.3_setosa
5.0_3.4_1.5_0.2_setosa
4.4_2.9_1.4_0.2_setosa
4.9_3.1_1.5_0.1_setosa
5.4_3.7_1.5_0.2_setosa
4.8_3.4_1.6_0.2_setosa
4.8_3.0_1.4_0.1_setosa
4.3_3.0_1.1_0.1_setosa
5.8_4.0_1.2_0.2_setosa
5.7_4.4_1.5_0.4_setosa
5.4_3.9_1.3_0.4_setosa
5.1_3.5_1.4_0.3_setosa
5.7_3.8_1.7_0.3_setosa
5.1_3.8_1.5_0.3_setosa
5.4_3.4_1.7_0.2_setosa
5.1_3.7_1.5_0.4_setosa
4.6_3.6_1.0_0.2_setosa
5.1_3.3_1.7_0.5_setosa
4.8_3.4_1.9_0.2_setosa
5.0_3.0_1.6_0.2_setosa
5.0_3.4_1.6_0.4_setosa
5.2_3.5_1.5_0.2_setosa
5.2_3.4_1.4_0.2_setosa
4.7_3.2_1.6_0.2_setosa
4.8_3.1_1.6_0.2_setosa
5.4_3.4_1.5_0.4_setosa
5.2_4.1_1.5_0.1_setosa
5.5_4.2_1.4_0.2_setosa
4.9_3.1_1.5_0.1_setosa
5.0_3.2_1.2_0.2_setosa
5.5_3.5_1.3_0.2_setosa
4.9_3.1_1.5_0.1_setosa
4.4_3.0_1.3_0.2_setosa
5.1_3.4_1.5_0.2_setosa
5.0_3.5_1.3_0.3_setosa
4.5_2.3_1.3_0.3_setosa
4.4_3.2_1.3_0.2_setosa
5.0_3.5_1.6_0.6_setosa
5.1_3.8_1.9_0.4_setosa
4.8_3.0_1.4_0.3_setosa
5.1_3.8_1.6_0.2_setosa
4.6_3.2_1.4_0.2_setosa
5.3_3.7_1.5_0.2_setosa
5.0_3.3_1.4_0.2_setosa
7.0_3.2_4.7_1.4_versicolor
6.4_3.2_4.5_1.5_versicolor
6.9_3.1_4.9_1.5_versicolor
5.5_2.3_4.0_1.3_versicolor
6.5_2.8_4.6_1.5_versicolor
5.7_2.8_4.5_1.3_versicolor
6.3_3.3_4.7_1.6_versicolor
4.9_2.4_3.3_1.0_versicolor
6.6_2.9_4.6_1.3_versicolor
5.2_2.7_3.9_1.4_versicolor
5.0_2.0_3.5_1.0_versicolor
5.9_3.0_4.2_1.5_versicolor
6.0_2.2_4.0_1.0_versicolor
6.1_2.9_4.7_1.4_versicolor
5.6_2.9_3.6_1.3_versicolor
6.7_3.1_4.4_1.4_versicolor
5.6_3.0_4.5_1.5_versicolor
5.8_2.7_4.1_1.0_versicolor
6.2_2.2_4.5_1.5_versicolor
5.6_2.5_3.9_1.1_versicolor
5.9_3.2_4.8_1.8_versicolor
6.1_2.8_4.0_1.3_versicolor
6.3_2.5_4.9_1.5_versicolor
6.1_2.8_4.7_1.2_versicolor
6.4_2.9_4.3_1.3_versicolor
6.6_3.0_4.4_1.4_versicolor
6.8_2.8_4.8_1.4_versicolor
6.7_3.0_5.0_1.7_versicolor
6.0_2.9_4.5_1.5_versicolor
5.7_2.6_3.5_1.0_versicolor
5.5_2.4_3.8_1.1_versicolor
5.5_2.4_3.7_1.0_versicolor
5.8_2.7_3.9_1.2_versicolor
6.0_2.7_5.1_1.6_versicolor
5.4_3.0_4.5_1.5_versicolor
6.0_3.4_4.5_1.6_versicolor
6.7_3.1_4.7_1.5_versicolor
6.3_2.3_4.4_1.3_versicolor
5.6_3.0_4.1_1.3_versicolor
5.5_2.5_4.0_1.3_versicolor
5.5_2.6_4.4_1.2_versicolor
6.1_3.0_4.6_1.4_versicolor
5.8_2.6_4.0_1.2_versicolor
5.0_2.3_3.3_1.0_versicolor
5.6_2.7_4.2_1.3_versicolor
5.7_3.0_4.2_1.2_versicolor
5.7_2.9_4.2_1.3_versicolor
6.2_2.9_4.3_1.3_versicolor
5.1_2.5_3.0_1.1_versicolor
5.7_2.8_4.1_1.3_versicolor
6.3_3.3_6.0_2.5_virginica
5.8_2.7_5.1_1.9_virginica
7.1_3.0_5.9_2.1_virginica
6.3_2.9_5.6_1.8_virginica
6.5_3.0_5.8_2.2_virginica
7.6_3.0_6.6_2.1_virginica
4.9_2.5_4.5_1.7_virginica
7.3_2.9_6.3_1.8_virginica
6.7_2.5_5.8_1.8_virginica
7.2_3.6_6.1_2.5_virginica
6.5_3.2_5.1_2.0_virginica
6.4_2.7_5.3_1.9_virginica
6.8_3.0_5.5_2.1_virginica
5.7_2.5_5.0_2.0_virginica
5.8_2.8_5.1_2.4_virginica
6.4_3.2_5.3_2.3_virginica
6.5_3.0_5.5_1.8_virginica
7.7_3.8_6.7_2.2_virginica
7.7_2.6_6.9_2.3_virginica
6.0_2.2_5.0_1.5_virginica
6.9_3.2_5.7_2.3_virginica
5.6_2.8_4.9_2.0_virginica
7.7_2.8_6.7_2.0_virginica
6.3_2.7_4.9_1.8_virginica
6.7_3.3_5.7_2.1_virginica
7.2_3.2_6.0_1.8_virginica
6.2_2.8_4.8_1.8_virginica
6.1_3.0_4.9_1.8_virginica
6.4_2.8_5.6_2.1_virginica
7.2_3.0_5.8_1.6_virginica
7.4_2.8_6.1_1.9_virginica
7.9_3.8_6.4_2.0_virginica
6.4_2.8_5.6_2.2_virginica
6.3_2.8_5.1_1.5_virginica
6.1_2.6_5.6_1.4_virginica
7.7_3.0_6.1_2.3_virginica
6.3_3.4_5.6_2.4_virginica
6.4_3.1_5.5_1.8_virginica
6.0_3.0_4.8_1.8_virginica
6.9_3.1_5.4_2.1_virginica
6.7_3.1_5.6_2.4_virginica
6.9_3.1_5.1_2.3_virginica
5.8_2.7_5.1_1.9_virginica
6.8_3.2_5.9_2.3_virginica
6.7_3.3_5.7_2.5_virginica
6.7_3.0_5.2_2.3_virginica
6.3_2.5_5.0_1.9_virginica
6.5_3.0_5.2_2.0_virginica
6.2_3.4_5.4_2.3_virginica
5.9_3.0_5.1_1.8_virginica

## `groupby`

- Split our dataframe into groups based on a key columns. In our case it will be **species**
- Remember `groupby` does NOT immediately compute something. We need to apply an aggregatation function (`sum` etc)

In [12]:
spec = iris.groupby("species")
spec

In [13]:
spec.head(10)

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
6             4.6          3.4           1.4          0.3      setosa
7             5.0          3.4           1.5          0.2      setosa
8             4.4          2.9           1.4          0.2      setosa
9             4.9          3.1           1.5          0.1      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
55            5.7          2.8           4.5          1.3  versicolor
56            6.3          3.3           4.7          1.6  versicolor
57            4.9          2.4           3.3          1.0  versicolor
58            6.6          2.9           4.6          1.3  versicolor
59            5.2          2.7           3.9          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
106           4.9          2.5           4.5          1.7   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica

In [15]:
spec.mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

## Exercise

 Use the Iris data set to do the following:

1. Add a `rank` column raanking `petal_length` in ascending order
2. Find the mean for each numeric olumn for each species
3. Create a new DataFrame per species (3 total)
4. Create 2 DataFrames:
    - one for **Sepal** info (length + width + species)
    - one for **Petal** info (length + width + species)